{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "opencommerce.name" . }}
    component: api
    chart: {{ template "opencommerce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "opencommerce.fullname" . }}-api
  namespace: {{ .Release.Namespace | quote }} 
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "opencommerce.name" . }}
      component: api
      release: {{ .Release.Name }}
  replicas: {{ .Values.api.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "opencommerce.name" . }}
        component: api
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.api.image.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.api.image.imagePullSecret }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-api
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        ports:
          - name: api
            containerPort: 3000
            protocol: TCP
        envFrom:
          - secretRef:
              name: {{ template "opencommerce.fullname" . }}
          - configMapRef:
              name: {{ template "opencommerce.fullname" . }}-api
{{- end }}