apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opencommerce.fullname" . }}
  labels:
    app: {{ template "opencommerce.name" . }}
    component: secrets
    chart: {{ template "opencommerce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  {{- if .Values.global.mongoUrl }}
  MONGO_URL: {{ .Values.global.mongoUrl | quote }}
  {{- else }}
  MONGO_URL: {{ printf "mongodb://root:%s@%s-mongodb-headless.%s.svc:27017/reaction?replicaSet=rs0&authSource=admin" .Values.mongodb.mongodbRootPassword ( include "opencommerce.fullname" . ) .Release.Namespace | quote }}
  {{- end }}
  {{- if .Values.global.mongoOplogUrl }}
  MONGO_OPLOG_URL: {{ .Values.global.mongoOplogUrl | quote }}
  {{- else }}
  MONGO_OPLOG_URL: {{ printf "mongodb://root:%s@%s-mongodb-headless.%s.svc:27017/local?replicaSet=rs0&authSource=admin" .Values.mongodb.mongodbRootPassword ( include "opencommerce.fullname" . ) .Release.Namespace | quote }}
  {{- end }}
  {{- if .Values.api.mailUrl }}
  MAIL_URL: {{ .Values.api.mailUrl | quote }}
  {{- end }}