{{- if .Values.storefront.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "opencommerce.name" . }}
    component: storefront
    chart: {{ template "opencommerce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "opencommerce.fullname" . }}-storefront
  namespace: {{ .Release.Namespace | quote }} 
data:
  ## Force UTC timezone
  TZ: "Etc/UTC"
  NODE_ENV: "production"
  CANONICAL_URL: {{ include "opencommerce.storefront.url" . | quote }}
  ENABLE_SPA_ROUTING: "true"
  BUILD_GRAPHQL_URL: {{ printf "%s/graphql" ( include "opencommerce.api.url" . ) | quote }}
  EXTERNAL_GRAPHQL_URL: {{ printf "%s/graphql" ( include "opencommerce.api.url" . ) | quote }}
  INTERNAL_GRAPHQL_URL: {{ printf "http://%s-api.%s.svc:3000/graphql" ( include "opencommerce.fullname" . ) .Release.Namespace | quote }}
  PORT: "4000"
  SESSION_SECRET: {{ .Values.storefront.sessionSecret | quote }}
  SEGMENT_ANALYTICS_SKIP_MINIMIZE: "true"
  SEGMENT_ANALYTICS_WRITE_KEY: {{ .Values.global.segmentKey | quote }}
  SESSION_MAX_AGE_MS: "2592000000"
  

{{- end }}